### ISSUE TITLE
Catch annoying timeout error for bootstrap nodes on startup

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#41]
When starting the example, there are always errors like:

```shell
DPT bootstrap error: Error: Timeout error: ping 5.1.83.226:30303
    at Timeout._onTimeout (/Users/hdrewes/Documents/DEV/EthereumJS/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/dpt/server.js:97:29)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
````
for unavailable bootstrap nodes. These should be caught and replaced with a proper logging output msg instead.

**Comment by holgerd77** [comment]
Will close this for now since this has for the moment sufficiently been solved by https://github.com/ethereumjs/common/pull/14 - see also this issue https://github.com/ethereumjs/ethereumjs-client/issues/28 on the client side. There might nevertheless be the need arising again to solve this more properly by better propagating the underlying root error to be handled more properly on the consuming side. So feel free to reopen then.
