### ISSUE TITLE
 Installation breaks on Node v12+

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#61]
Installation on the library breaks using Node 12 (v12.15.0) or 13 (v13.13.0) (Mac OS Mojave 10.14.1), following output:

```shell
$ npm install

> sha3@1.2.0 install /ethereumjs-devp2p/node_modules/sha3
> node-gyp rebuild

  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:4:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/addon.cpp:4:
In file included from ../../nan/nan.h:197:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(v8::Isolate::GetCurrent()->GetCurrentContext())          \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Caches/node-gyp/13.13.0/include/node/v8.h:2762:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../src/addon.cpp:4:
In file included from ../../nan/nan.h:197:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
 
[ MORE STUFF ]

fatal error: too many errors emitted, stopping now [-ferror-limit=]
5 warnings and 20 errors generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/.nvm/versions/node/v13.13.0/bin/node" "/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Documents/DEV/EthereumJS/ethereumjs-devp2p/node_modules/sha3
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN request-promise-core@1.1.3 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.8 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of tslint@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-sonarts@1.9.0 requires a peer of tslint@^5.11.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-04-20T15_21_21_194Z-debug.log
``` 

@PhilippLgh Is this something you can reproduce on your machine locally and if so can you please have a look at it before we release?

**Comment by PhilippLgh** [comment]
was running the examples with v12.10 and it was working fine.. Can play with it a little bit but ideally the CI would test this

**Comment by PhilippLgh** [comment]
It actually looks like GH Actions can successfully build on 12.x and 13.x https://github.com/ethereumjs/ethereumjs-devp2p/runs/596033309?check_suite_focus=true

**Comment by holgerd77** [comment]
Ah, got it, was this damn local `package-lock.json` file. Stumbling over this again and again (without too much learning it seems).

Can be closed here. 😄
